repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
    - id: flake8
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.0
  hooks:
    - id: bandit
      exclude: ^test(s)?/  # keep in sync with .bandit file
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
      exclude: ^tests/  # keep in sync with mypy.ini
