name: Source package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq swig libpcsclite-dev
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run unit tests
        run: poetry run pytest

      - name: Create source package
        run: |
          poetry build
          mkdir artifacts
          export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          mv dist/canokey_manager-*.tar.gz artifacts/canokey_manager-$REF.tar.gz
          mv dist/canokey_manager-*.whl artifacts/canokey_manager-$REF.whl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: canokey-manager-source-package
          path: artifacts

  docs:
    runs-on: ubuntu-latest
    name: Build sphinx documentation

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq swig libpcsclite-dev
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build sphinx documentation
        run: poetry run make -C docs/ html

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: yubikey-manager-docs
          path: docs/_build/html
