name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'
          cache: poetry

      - name: Install dependencies
        run: |
          sudo apt-get install -qq swig libpcsclite-dev
          poetry install

      # - name: Run unit tests
      #   run: poetry run pytest

      - name: Run CLI
        run: |
          poetry build
          pip install dist/canokey*.whl
          ckman --version
          [[ -z "$(ckman --version | grep -E "not found|missing")" ]]

      - name: PyInstaller
        run: |
          poetry run pyinstaller ykman.spec
          dist/ckman/ckman --version
          [[ -z "$(dist/ckman/ckman --version | grep -E "not found|missing")" ]]
          export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          mv dist/ckman dist/ckman-$REF

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ckman-builds-ubuntu
          path: dist
