name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run pytest -v

      - name: Build
        run: poetry build

      - name: Install from tar.gz
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install dist/*.tar.gz
          ckman --version
          [[ -z "$(ckman --version | grep -E "not found|missing")" ]]
          pip uninstall -y yubikey-manager

      - name: Install from wheel
        shell: bash
        run: |
          pip install dist/*.whl
          ckman --version
          [[ -z "$(ckman --version | grep -E "not found|missing")" ]]
          pip uninstall -y yubikey-manager

      - name: PyInstaller
        shell: bash
        run: |
          poetry run pyinstaller ykman.spec
          dist/ckman/ckman.exe --version
          [[ -z "$(dist/ckman/ckman.exe --version | grep -E "not found|missing")" ]]

      - name: Copy scripts
        shell: bash
        run: cp -r resources/win dist/scripts

      - name: Build installer
        working-directory: ./dist
        run: .\scripts\make_msi.ps1

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ckman-builds-windows
          path: dist
