name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          choco install swig
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        shell: powershell

      - name: Run unit tests
        run: poetry run pytest -v

      - name: Build
        run: poetry build

      - name: Install from tar.gz
        shell: bash
        run: |
          pip install dist/*.tar.gz
          ykman --version
          [[ -z "$(ykman --version | grep -E "not found|missing")" ]]
          pip uninstall -y yubikey-manager

      - name: Install from wheel
        shell: bash
        run: |
          pip install dist/*.whl
          ykman --version
          [[ -z "$(ykman --version | grep -E "not found|missing")" ]]
          pip uninstall -y yubikey-manager

      - name: Clone PyInstaller
        uses: actions/checkout@v2
        with:
          repository: pyinstaller/pyinstaller
          ref: 90431c010a23b1c9080fcb44f932d4615bb71825
          path: pyinstaller

      - name: Build PyInstaller
        shell: bash
        run: |
          cd pyinstaller/bootloader
          python waf distclean all
          cd ..
          pip install .
          cd ..

      - name: Build exe
        shell: bash
        run: |
          pip install dist/*.whl
          pyinstaller ykman.spec
          dist/ykman.exe --version
          [[ -z "$(dist/ykman.exe --version | grep -E "not found|missing")" ]]
          export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          mv dist/ykman.exe dist/ykman-$REF.exe

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: ykman-builds-windows
          path: dist
